workflows:
  ios-sideload:
    name: iOS IPA for Sideloadly
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      groups:
        - ios_signing_credentials

      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.ticks.app

      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: find . -name "Podfile" -execdir pod install \;

      - name: Set up code signing
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(date +%s)

    artifacts:
      - build/ios/ipa/*.ipa

